"""Model-card rendering for published checkpoints.

Generates the Hub ``README.md`` of one selected checkpoint in the layout of
the hand-written InflaReddert card (front matter, lineage, labels, usage,
limitations, data, procedure, evaluation, citation) from the facts the
``upload`` task collects into a :class:`CheckpointCard`. The result is a
*draft to review*, not a final text — which is why every repository is
created private (``hub.private`` in ``config.yml``).

The renderer is pure: no I/O, no network, no torch. Everything it prints
comes from the dataclasses below.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from yaml import safe_dump

if TYPE_CHECKING:
    from reddit.core.config import ModelKind

PAPER = (
    "Del Monaco, A., Longo, L., Marcucci, J. & Tafani, I. (2026).\n"
    "> *Reddit's 'pulse' on US inflation: forecasting with large language models.*\n"
    "> Journal of Applied Econometrics, forthcoming.\n"
    "> Working-paper version: Banca d'Italia, Questioni di Economia e Finanza\n"
    "> (Occasional Papers) No. 1028, June 2026, doi:10.32057/0.QEF.2026.1028."
)
REPOSITORY = "https://github.com/andrea-dm/reddit-pulse"
BIBTEX = """```bibtex
@article{delmonaco2026reddit,
  title   = {Reddit's `pulse' on {US} inflation: forecasting with large language models},
  author  = {Del Monaco, Andrea and Longo, Luigi and Marcucci, Juri and Tafani, Irene},
  journal = {Journal of Applied Econometrics},
  year    = {2026},
  note    = {forthcoming},
}

@techreport{delmonaco2026reddit_qef,
  title       = {Reddit's `pulse' on {US} inflation: forecasting with large language models},
  author      = {Del Monaco, Andrea and Longo, Luigi and Marcucci, Juri and Tafani, Irene},
  institution = {Banca d'Italia},
  series      = {Questioni di Economia e Finanza (Occasional Papers)},
  number      = {1028},
  year        = {2026},
  month       = jun,
  doi         = {10.32057/0.QEF.2026.1028},
}
```"""
DISCLAIMER = (
    "The views expressed in the paper are those of the authors and do not\n"
    "necessarily reflect those of the Bank of Italy, the Eurosystem, or the\n"
    "European Commission."
)
# What the License section says per base-model license id.
LICENSE_NOTES: dict[str, str] = {
    "apache-2.0": "Apache License, Version 2.0, inherited from the base model.",
    "mit": "MIT license, inherited from the base model.",
    "gemma": (
        "The base model is released under the [Gemma Terms of Use](https://ai.google.dev/gemma/terms), "
        "which this adapter inherits; the terms are kept on Google's page and not redistributed here."
    ),
    "llama3.2": (
        "The base model is released under the Llama 3.2 Community License, which this adapter inherits "
        "(*Built with Llama*)."
    ),
}
# How the Files table describes each published file.
FILE_NOTES: dict[str, str] = {
    "adapter_model.safetensors": (
        "DoRA adapter weights and the three-way classification head (base weights are not redistributed)"
    ),
    "adapter_config.json": "PEFT adapter configuration (base model, rank, target modules)",
    "model.safetensors": "full weights",
    "config.json": "architecture, three-way head and label map",
    "tokenizer.json": "tokenizer",
    "tokenizer_config.json": "tokenizer settings (pad token, padding side)",
    "chat_template.jinja": "chat template inherited from the base tokenizer (unused by the classifier)",
    "training_args.json": "the `transformers.TrainingArguments` of the selected run",
    "training_config.yml": "dataset split, hyperparameters, seed list and label map from the project config",
    "evaluation/seeds_test_metrics.csv": "test metrics of every split seed",
    "evaluation/seeds_validation_metrics.csv": "validation metrics of every split seed",
    "README.md": "this card",
}

# Metric key in the dumps -> column heading in the card, in table order.
METRIC_COLUMNS: tuple[tuple[str, str], ...] = (
    ("accuracy", "accuracy"),
    ("f1_weighted", "F1 weighted"),
    ("f1_macro", "F1 macro"),
    ("precision_macro", "precision macro"),
    ("recall_macro", "recall macro"),
    ("roc_auc", "ROC-AUC"),
)
RANKING_METRIC = "f1_weighted"
COMMON_TAGS: tuple[str, ...] = ("economics", "finance", "inflation", "inflation-expectations", "reddit")
# Shown under every card's title: the published checkpoints come from a
# retraining, so their numbers are not the paper's.
RETRAINING_NOTICE = (
    "> **Retrained checkpoint.** This model was trained again after the paper, on the\n"
    "> same gold dataset and with the same seed protocol. The metrics on this card come\n"
    "> from that retraining and may differ from the ones reported in the paper."
)
GENERATED_NOTICE = (
    "<!-- Generated by `reddit upload`. Review before making the repository public: the\n"
    "     limitations section is generic, and the per-class breakdown of the hand-written\n"
    "     cards is not produced automatically. -->"
)


@dataclass(frozen=True, slots=True)
class LabelRow:
    """One row of the labels table.

    Attributes:
        id: Classification-head index.
        name: Label name (``down``/``neutral``/``up``).
        encoding: Signed trend encoding used in the paper's corpus files.
    """

    id: int
    name: str
    encoding: int


PROJECT_NAME = "Reddit-pulse"
# How each base model's own card spells its name (checked against the Hub
# cards): the generated title is "Reddit-pulse <base> <method>".
BASE_MODEL_NAMES: dict[str, str] = {
    "google/gemma-2-2b": "Gemma 2 2B",
    "google/gemma-2-9b": "Gemma 2 9B",
    "google/gemma-2-27b": "Gemma 2 27B",
    "meta-llama/Llama-3.1-8B": "Llama 3.1 8B",
    "meta-llama/Llama-3.2-1B": "Llama 3.2 1B",
    "meta-llama/Llama-3.2-3B": "Llama 3.2 3B",
    "Qwen/Qwen2.5-0.5B": "Qwen2.5 0.5B",
    "Qwen/Qwen2.5-1.5B": "Qwen2.5 1.5B",
    "Qwen/Qwen2.5-7B": "Qwen2.5 7B",
    "google-bert/bert-base-uncased": "BERT base uncased",
    "MAPAi/InflaBERT": "InflaBERT",
    "ProsusAI/finbert": "FinBERT",
}


def base_model_display_name(base_model: str) -> str:
    """The base model's name as its own card spells it.

    Args:
        base_model: Hub id of the base checkpoint (``google/gemma-2-2b``).

    Returns:
        The entry of :data:`BASE_MODEL_NAMES`, or, for an unlisted base, its
        repository name with dashes turned into spaces (``gemma-2-2b`` ->
        ``gemma 2 2b``) so a new family still gets a readable title.
    """
    return BASE_MODEL_NAMES.get(base_model, base_model.rsplit("/", 1)[-1].replace("-", " "))


@dataclass(frozen=True, slots=True)
class SeedMetrics:
    """Validation and test metrics of one split seed.

    Attributes:
        seed: The split seed.
        test: Test-split metrics keyed as in the ``dist_*_test_metrics``
            dumps (``accuracy``, ``f1_weighted``, ...).
        validation: Validation-split metrics, same keys; may be empty.
    """

    seed: int
    test: dict[str, float]
    validation: dict[str, float]


@dataclass(frozen=True, slots=True)
class CheckpointCard:
    """Everything the model card of one selected checkpoint says.

    Attributes:
        repo_id: Hub repository (``namespace/name``) the card is written for.
        model_name: Short model name from ``config.yml`` (``qwen2.5_0.5b``).
        base_model: Hub id of the base checkpoint.
        kind: ``"llm"`` (PEFT adapter) or ``"bert"`` (full fine-tune).
        method: ``"qdora"``/``"xqdora"`` for adapters, ``"-"`` for encoders.
        seed: The split seed of the published (median) checkpoint.
        labels: The label set, ordered by head index.
        seeds: Every seed of the run the checkpoint was selected from.
        hyperparameters: ``(setting, value)`` rows of the procedure table.
        gold_counts: Gold-set rows per label, most frequent first.
        split_shares: ``(train, validation, test)`` fractions of the gold set.
        max_length: Tokenizer truncation length used in training and inference.
        base_license: SPDX-style license id of the base model, if known.
        files: Every file the repository publishes, for the Files table.
        license_files: The base model's license/use-policy files carried
            along (a subset of ``files``).
        corpus_shares: ``{"submissions"/"comments": {label: share}}`` from
            the corpus this checkpoint labelled; empty when it was not run.
    """

    repo_id: str
    model_name: str
    base_model: str
    kind: ModelKind
    method: str
    seed: int
    labels: tuple[LabelRow, ...]
    seeds: tuple[SeedMetrics, ...]
    hyperparameters: tuple[tuple[str, str], ...]
    gold_counts: dict[str, int]
    split_shares: tuple[float, float, float]
    max_length: int
    base_license: str | None = None
    files: tuple[str, ...] = ()
    license_files: tuple[str, ...] = ()
    corpus_shares: dict[str, dict[str, float]] | None = None

    @property
    def is_adapter(self) -> bool:
        """PEFT adapter (decoder LLM) rather than a fully fine-tuned encoder."""
        return self.kind != "bert"

    @property
    def name(self) -> str:
        """The repository name without its namespace."""
        return self.repo_id.rsplit("/", 1)[-1]

    @property
    def title(self) -> str:
        """The card's human-readable name: ``Reddit-pulse Gemma 2 2B QDoRA+``.

        Encoders carry no method: ``Reddit-pulse InflaBERT``.
        """
        parts = [PROJECT_NAME, base_model_display_name(self.base_model)]
        if self.is_adapter:
            parts.append(_method_label(self.method))
        return " ".join(parts)

    @property
    def selected(self) -> SeedMetrics | None:
        """Metrics of the published seed, if the run's dumps carried them."""
        return next((s for s in self.seeds if s.seed == self.seed), None)


def render_model_card(card: CheckpointCard) -> str:
    """Render the full ``README.md`` for one checkpoint.

    Args:
        card: The facts to print.

    Returns:
        Markdown text with YAML front matter, ready to be written to the
        repository folder.
    """
    sections = (
        _front_matter(card),
        GENERATED_NOTICE,
        _introduction(card),
        _lineage(card),
        _labels(card),
        _usage(card),
        _limitations(card),
        _training_data(card),
        _procedure(card),
        _evaluation(card),
        _corpus_labelling(card),
        _files(card),
        _reproducing(card),
        _citation(),
        _license(card),
    )
    return "\n\n".join(section.strip("\n") for section in sections) + "\n"


def _fmt(value: float | None) -> str:
    """Three-decimal rendering of a metric; a dash when it is missing."""
    return "—" if value is None else f"{value:.3f}"


def _front_matter(card: CheckpointCard) -> str:
    """The YAML metadata block the Hub indexes (base model, library, tags, results)."""
    metadata: dict[str, Any] = {"language": ["en"]}
    if card.base_license:
        metadata["license"] = card.base_license
    metadata |= {
        "library_name": "peft" if card.is_adapter else "transformers",
        "base_model": card.base_model,
        "base_model_relation": "adapter" if card.is_adapter else "finetune",
        "pipeline_tag": "text-classification",
        "tags": list(COMMON_TAGS) + (["peft", "lora", "dora", card.method] if card.is_adapter else []),
        "metrics": ["accuracy", "f1", "roc_auc"],
    }
    if (selected := card.selected) is not None:
        metadata["model-index"] = [
            {
                "name": card.title,
                "results": [
                    {
                        "task": {
                            "type": "text-classification",
                            "name": "Directional inflation-expectation classification (up / neutral / down)",
                        },
                        "dataset": {
                            "name": (
                                "Reddit inflation gold set (Del Monaco, Longo, Marcucci & Tafani, 2026), "
                                f"held-out test split of seed {card.seed}"
                            ),
                            "type": "reddit-inflation-gold-set",
                            "split": "test",
                        },
                        "metrics": [
                            {"type": "accuracy", "value": round(selected.test.get("accuracy", 0.0), 4)},
                            {
                                "type": "f1",
                                "value": round(selected.test.get("f1_weighted", 0.0), 4),
                                "name": "F1 (weighted)",
                            },
                            {"type": "f1", "value": round(selected.test.get("f1_macro", 0.0), 4), "name": "F1 (macro)"},
                            {
                                "type": "roc_auc",
                                "value": round(selected.test.get("roc_auc", 0.0), 4),
                                "name": "ROC-AUC (macro, one-vs-rest)",
                            },
                        ],
                    }
                ],
            }
        ]
    return "---\n" + safe_dump(metadata, sort_keys=False, allow_unicode=True, width=100) + "---"


def _method_label(method: str) -> str:
    """The paper's spelling of a fine-tuning method (``qdora`` -> ``QDoRA+``)."""
    return {"qdora": "QDoRA+", "xqdora": "xQDoRA+"}.get(method, method)


def _introduction(card: CheckpointCard) -> str:
    what = (
        f"a **{_method_label(card.method)}** adapter on "
        f"[`{card.base_model}`](https://huggingface.co/{card.base_model}) (4-bit NF4 base, DoRA adapters "
        "on the attention projections, LoRA+ learning rates)"
        if card.is_adapter
        else f"a full fine-tune of [`{card.base_model}`](https://huggingface.co/{card.base_model})"
    )
    return f"""# {card.title}

{RETRAINING_NOTICE}

**{card.title}** is a three-way *directional* inflation-expectation classifier
for short English texts about the economy, fine-tuned on Reddit submission
titles: {what}. Given a title (or any sentence-length text), it predicts
whether the text conveys that inflation / prices are going **up**, going
**down**, or carries **no directional signal** (**neutral**).

It is *not* a sentiment model: "inflation falls sharply" is *good* news but
labelled **down**; "rents are out of control" is *bad* news but labelled
**up**. The direction is about the price level, not the mood.

The checkpoint is one of the small-model classifiers behind the Reddit
inflation signal in

> {PAPER}

The fine-tuning and full-corpus inference code lives at
[andrea-dm/reddit-pulse]({REPOSITORY})."""


def _lineage(card: CheckpointCard) -> str:
    stage = "QDoRA+/xQDoRA+ PEFT adapter" if card.is_adapter else "Full fine-tuning"
    return f"""## Model lineage

| Stage | Model | Notes |
|---|---|---|
| Base | [`{card.base_model}`](https://huggingface.co/{card.base_model}) | Pre-trained checkpoint |
| **This checkpoint** | **`{card.repo_id}`** | {stage} on Reddit titles, three-way head **down / neutral / up** |"""


def _labels(card: CheckpointCard) -> str:
    rows = "\n".join(f"| {row.id} | `{row.name}` | `{row.encoding:+d}` |" for row in card.labels)
    return f"""## Labels

| id | label | encoding used in the paper's corpus files |
|---|---|---|
{rows}"""


def _usage(card: CheckpointCard) -> str:
    encoding = ", ".join(f'"{row.name}": {row.encoding}' for row in card.labels)
    if not card.is_adapter:
        return f"""## How to use

```python
from transformers import pipeline

clf = pipeline("text-classification", model="{card.repo_id}")
clf("Fed officials warn prices will keep climbing as CPI hits 40-year high")
```"""
    return f"""## How to use

The adapter is loaded on top of the 4-bit quantized base model, exactly as
it was trained (`bitsandbytes` and `peft` required). `config.json` in this
repository carries the three-way head, the label names and the pad token,
so no argument beyond the repository name is needed:

```python
import torch
from peft import PeftModel
from transformers import (
    AutoConfig,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    BitsAndBytesConfig,
)

name = "{card.repo_id}"
tokenizer = AutoTokenizer.from_pretrained(name)
tokenizer.padding_side = "left"
config = AutoConfig.from_pretrained(name)
base = AutoModelForSequenceClassification.from_pretrained(
    "{card.base_model}",
    config=config,
    dtype=torch.bfloat16,
    quantization_config=BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
    ),
    device_map="auto",
)
model = PeftModel.from_pretrained(base, name).eval()
encoding = {{{encoding}}}

texts = [
    "Inflation expectations drop to lowest level since 2021, NY Fed survey shows",
    "What is the difference between CPI and PCE?",
]
with torch.inference_mode():
    batch = tokenizer(texts, padding=True, truncation=True, max_length={card.max_length}, return_tensors="pt")
    ids = model(**batch.to(model.device)).logits.argmax(dim=-1).tolist()

print([encoding[config.id2label[i]] for i in ids])  # [-1, 0]
```

Do **not** hand the repository name to `AutoModelForSequenceClassification`
directly: transformers' adapter shortcut rebuilds this DoRA adapter with
different logits than the trained model."""


def _limitations(card: CheckpointCard) -> str:
    del card  # the same caveats hold for every checkpoint of the family
    return """## Intended use and limitations

**Intended use.** Labelling large volumes of short, informal, English,
economy-related texts (Reddit titles and comments, headlines, social media
posts) with a directional inflation signal that is then *aggregated* over
time — the paper's use case. The model is a building block for a
high-frequency indicator, not a stand-alone oracle.

**Limitations.**

- **Single predictions are noisy.** The value of the model comes from
  averaging thousands of predictions per period, where idiosyncratic errors
  wash out. Do not rely on any single label.
- **Domain and register.** Trained on r/economy, r/Economics and
  r/wallstreetbets titles about *US* inflation from 2008 to 2022. Other
  countries, other registers and post-2022 vocabulary are out of distribution.
- **Class imbalance.** `down` is the minority class of the gold set and the
  hardest one; the loss was class-balanced during training, but `down`
  recall remains lower.
- **Short texts.** Fine-tuned on titles (median 11 words, max 52). Long
  comments are truncated and were not seen during training.
- **Direction, not stance or sentiment.** The model does not say whether the
  author *wants* inflation to move, nor whether the news is good or bad;
  only which way prices are said to be going."""


def _training_data(card: CheckpointCard) -> str:
    total = sum(card.gold_counts.values())
    rows = "\n".join(
        f"| {label} | {count:,d} | {100 * count / total:.1f} % |" for label, count in card.gold_counts.items()
    )
    table = f"\n| label | titles | share |\n|---|---|---|\n{rows}\n" if total else ""
    return f"""## Training data

The gold set is a hand-labelled sample of **{total:,d} Reddit submission titles**
from r/economy, r/Economics and r/wallstreetbets, dated February 2008 to
December 2022. Labels were produced by a human-in-the-loop protocol (manual
annotation assisted by zero-shot LLaMA-70B, a fine-tuned LLaMA-8B classifier
and ChatGPT-assisted adjudication of disagreements) described in the paper.
The gold set itself is not redistributed here.
{table}"""


def _procedure(card: CheckpointCard) -> str:
    train, validation, test = card.split_shares
    total = sum(card.gold_counts.values())
    sizes = ""
    if total:
        n_test = round(total * test)
        n_validation = round(total * validation)
        sizes = f" ({total - n_validation - n_test} / {n_validation} / {n_test} titles)"
    n_seeds = len(card.seeds)
    rows = "\n".join(f"| {setting} | {value} |" for setting, value in card.hyperparameters)
    return f"""## Training procedure

### Seed protocol and model selection

The paper's protocol asks how sensitive the classifier is to *which* titles
it is trained on, so it separates two sources of randomness:

- **{n_seeds} split seeds** each draw a different stratified
  **{100 * train:.0f} / {100 * validation:.0f} / {100 * test:.0f} %** train / validation / test
  partition{sizes} of the same gold set.
- **One fixed seed** governs everything else: adapter and head
  initialisation, batch shuffling and dropout. Every split therefore trains
  *the same model the same way* on different data.

Each split is fine-tuned independently; the checkpoint with the **median**
test weighted-F1 across the runs (the upper median) is kept and the others
discarded. The result is a *typical* run, not the best one. This checkpoint
is split seed **{card.seed}**.

### Hyperparameters

| | |
|---|---|
{rows}

The exact `TrainingArguments` are in [`training_args.json`](training_args.json)
and the governing configuration extract in
[`training_config.yml`](training_config.yml)."""


def _metric_cells(metrics: dict[str, float]) -> str:
    return " | ".join(_fmt(metrics.get(key)) for key, _ in METRIC_COLUMNS)


def _evaluation(card: CheckpointCard) -> str:
    if not card.seeds:
        return "## Evaluation\n\nNo per-seed metrics dump was found for this run."
    headings = " | ".join(heading for _, heading in METRIC_COLUMNS)
    separator = "|".join("---" for _ in METRIC_COLUMNS)
    selected = card.selected
    lines = [f"## Evaluation\n\n### Selected checkpoint (split seed {card.seed})\n"]
    if selected is not None:
        lines.append(f"| split | {headings} |\n|---|{separator}|")
        if selected.validation:
            lines.append(f"| validation | {_metric_cells(selected.validation)} |")
        lines.append(f"| **test** | {_metric_cells(selected.test)} |")
    else:
        lines.append("Its metrics were not found in the run's dumps.")
    lines.append(
        f"\n### Split sensitivity across the {len(card.seeds)} seeds\n\n"
        "Test metrics of every run, sorted by weighted F1; the selected checkpoint is marked.\n\n"
        f"| seed | {headings} | |\n|---|{separator}|---|"
    )
    ranked = sorted(card.seeds, key=lambda s: s.test.get(RANKING_METRIC, float("nan")), reverse=True)
    lines.extend(
        f"| {s.seed} | {_metric_cells(s.test)} | {'**selected**' if s.seed == card.seed else ''} |" for s in ranked
    )
    lines.append("\nThe full tables are in [`evaluation/`](evaluation/).")
    return "\n".join(lines)


def _corpus_labelling(card: CheckpointCard) -> str:
    """Label shares over the paper's corpus, when the checkpoint was run over it."""
    if not card.corpus_shares:
        return ""
    names = [row.name for row in card.labels]
    header = "| | " + " | ".join(names) + " |\n|---|" + "|".join("---" for _ in names) + "|"
    rows = "\n".join(
        f"| {corpus_pass} | " + " | ".join(f"{100 * shares.get(name, 0.0):.1f} %" for name in names) + " |"
        for corpus_pass, shares in card.corpus_shares.items()
    )
    return f"""## Corpus labelling in the paper

Applied to the paper's filtered corpus (r/economy, r/Economics,
r/wallstreetbets, 2008-2022), this checkpoint assigns the labels in these
proportions:

{header}
{rows}"""


def _files(card: CheckpointCard) -> str:
    rows = "\n".join(f"| `{name}` | {_describe_file(card, name)} |" for name in dict.fromkeys(card.files))
    return f"""## Files

| file | content |
|---|---|
{rows}"""


def _describe_file(card: CheckpointCard, name: str) -> str:
    if name in card.license_files:
        return "license / use-policy notice of the base model, redistributed as its terms require"
    return FILE_NOTES.get(name, "")


def _reproducing(card: CheckpointCard) -> str:
    return f"""## Reproducing

```bash
git clone {REPOSITORY} && cd reddit-pulse
uv venv && uv pip install -e .
reddit run --model {card.model_name} --gpu 0     # every split seed, median selection, corpus labelling
reddit upload --model {card.model_name}          # this repository, from the selected checkpoint
```

The gold set (`data/labelled.xlsx`) and the subreddit corpus are not part of
the repository; see the paper for the data-construction stages."""


def _citation() -> str:
    return f"""## Citation

If you use this model, please cite the paper it was built for:

{BIBTEX}"""


def _license(card: CheckpointCard) -> str:
    if card.base_license:
        note = LICENSE_NOTES.get(card.base_license, f"`{card.base_license}`, inherited from the base model.")
    else:
        note = (
            f"The base model `{card.base_model}` declares no license on its card; check its repository "
            "before reusing this checkpoint."
        )
    included = (
        "The upstream notices are included: " + ", ".join(f"[`{f}`]({f})" for f in card.license_files) + "."
        if card.license_files
        else "The base repository ships no license file to carry along."
    )
    return f"""## License

{note} {included}

{DISCLAIMER}"""
